name: Deploy on Developer Docs

# Run the deployment only when code is committed to teh branch.
on:
  push:
    branches:
      # Remove "- developer-doc-github-action" once implemented and keep just `master` branch.
      - master
      - developer-doc-github-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: rsync over ssh
      run: ssh -T ${{ secrets.DEVELOPER_DOC_SSH_HOST }}@${{ secrets.DEVELOPER_DOC_SSH_USERNAME }}
