name: Deploy on Developer Docs

# Run the deployment only when code is committed to teh branch.
on:
  push:
    branches:
      # Remove "- developer-doc-github-action" once implemented and keep just `master` branch.
      - master
      - developer-doc-github-action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: wp parser create ${{ secrets.DEVELOPER_DOC_SSH_PATH }}wp-content/themes/astra --user=1 --url=https://developers.wpastra.com/astra-theme/ --path=/home/runcloud/webapps/developers-wpastra/
