name: Playwright

on: pull_request

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

    - name: Install dependencies
        run: npm install

    - name: Start Docker environment
      run: npm run env:up:gh

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --reporter=line --shard=${{ matrix.shard }}/${{ strategy.job-total }}

    - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

    - name: Stop Docker environment
      run: npm run env:stop
      if: always()
