name: Playwright Tests
on:
  # push:
  #   branches: [ main, next-release ]
  pull_request:
    # branches: [ main, next-release ]
jobs:
  test:
    name: E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
     strategy:
            fail-fast: false
            matrix:
                part: [1, 2]
                node: ['14']
                directory:
                  - tests/play/simple-tests
                  - tests/play/complex-tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: npm

    - name: Npm install and build
              run: |
                  npm install

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Start Docker environment
              run: |
                  npm run env:start
              env:
                COMPOSE_INTERACTIVE_NO_CLI: true

    - name: Run Playwright tests
      run: npx playwright test --reporter=line

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
