name: Adding Release PR checklist to the comment

on:
  pull_request:
    types: [ labeled ]

jobs:
  update_pr:
    name: PR update
    if: ${{ github.event.label.name == 'Release PR checklist' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ master == ${{ github.base_ref }} || release-candidate == ${{ github.base_ref }} || next-release == ${{ github.base_ref }} ]]; then
              echo ::set-output name=match::true
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: Final release PR. Please check all the checklist below before merging.
      - run: |
          if [[ steps.fc.outputs.comment-id == 0 ]]; then
              echo ::set-output name=comment_exists::true
          fi
          echo steps.check-branch.outputs.comment_exists

      - uses: tzkhan/pr-update-action@v2
        if: |
          ( steps.check-branch.outputs.match == 'true' ) && ( steps.check-branch.outputs.comment_exists != 'true' )
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '[A-Za-z\d-_.\\/]+'
          title-template: 'Build: Release PR'
          title-update-action: 'prefix'

      - uses: peter-evans/create-or-update-comment@v1
        if: |
          ( steps.check-branch.outputs.match == 'true' ) && ( steps.check-branch.outputs.comment_exists != 'true' )
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ### Final release PR. Please check all the checklist below before merging.
            ---

            ### Checklist:
            - [ ] Finalize changelog.txt
            - [ ] Add doc links in the changelog.txt
            - [ ] Change minimum addon update version - `ASTRA_EXT_MIN_VER`
            - [ ] Run to update packages        : `npm audit fix`
            - [ ] Run to produce minified files : `grunt minify`
            - [ ] Run to update Google Fonts    : `grunt google-fonts`
            - [ ] PHPCS - vendor/bin/phpcs
            - [ ] Run to update version number  : `grunt version-bump --ver=<version-number>`
            - [ ] Check the Background Process function version
            - [ ] Update - Tested Upto - style.css & readme.txt
            - [ ] Update Readme.txt file and then run: `grunt readme`
            - [ ] Generate POT file             : `wp i18n make-pot wp-content/themes/astra wp-content/themes/astra/languages/astra.pot`
            - [ ] Make sure all the GitHub PR checks are passed
            - [ ] Add draft Release notes on github
            - [ ] Add draft changelogs to wpastra.com
            - [ ] Open PR to backport branch to `next-release`
            ---
