name: PR update

on:
  pull_request:
    types: [ labeled ]

jobs:
  update_pr:
    name: PR update
    if: ${{ github.event.label.name == 'Release PR checklist' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.base_ref }} == master || ${{ github.base_ref }} == release-candidate || ${{ github.base_ref }} == next-release ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '[A-Za-z\d-_.\\/]+'
          title-template: 'Build: Release PR'
          title-update-action: 'replace'
          body-uppercase-base-match: false

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Description
            - Final release PR. Please check all the checklist below in the same sequence before merging.
            ---

            ### Checklist:
            - [ ] Finalize changelog.txt
            - [ ] Add doc links in the changelog.txt
            - [ ] Update Graupi
            - [ ] Update BSF Analytics
            - [ ] PHPCS
            - [ ] Run to update packages        : `npm audit fix`
            - [ ] Run to produce minified files : `grunt minify`
            - [ ] Change minimum theme version - const - ASTRA_THEME_MIN_VER
            - [ ] Run to update version number  : `grunt version-bump --ver=<version-number>`
            - [ ] Check the Background Process function version
            - [ ] Update - Tested Upto - style.css & readme.txt
            - [ ] Update Readme.txt file and then run: `grunt readme`
            - [ ] Generate POT file             : `grunt i18n`
            - [ ] Upload languages POT file on translation brainstrom force website - https://translate.brainstormforce.com/glotpress/projects/astra-addon/import-originals/
            - [ ] Export translation files and update them in languages folder of Astra Addon
            - [ ] Add draft Release notes on github
            - [ ] Add draft changelogs to wpastra.com
            - [ ] Open PR to backport branch to `next-release`
