name: Sync branches to developement
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: 'Sync development'
          target_branch: 'development'
          github_token: ${{ github.token }}
